-- MYSQL
SELECT CART_ID
FROM (
	SELECT 
		CART_ID, 
    	NAME, 
		COUNT(CASE WHEN NAME = "요거트" THEN 1 END) as Y_C,
    	COUNT(CASE WHEN NAME = "우유" THEN 1 END) as M_C
	FROM CART_PRODUCTS
	WHERE NAME = "우유" OR NAME = "요거트"
	GROUP BY CART_ID) AS AGGREGATE
WHERE Y_C >= 1 AND M_C >= 1;
